export interface Rectangle{left:number;top:number;right:number;bottom:number}
export interface CameraCenterInput{scrollX:number;scrollY:number;viewportWidth:number;viewportHeight:number;zoom:number;canvas:Rectangle;container:Rectangle;mapWidth:number;mapHeight:number}
export interface CameraCenter{x:number;y:number}
export function constrainCameraCenter(input:CameraCenterInput):CameraCenter{const scaleX=(input.canvas.right-input.canvas.left)/input.mapWidth,scaleY=(input.canvas.bottom-input.canvas.top)/input.mapHeight,visiblePixelsX=Math.max(0,Math.min(input.canvas.right,input.container.right)-Math.max(input.canvas.left,input.container.left)),visiblePixelsY=Math.max(0,Math.min(input.canvas.bottom,input.container.bottom)-Math.max(input.canvas.top,input.container.top)),visibleWorldWidth=Math.min(input.mapWidth,visiblePixelsX/scaleX/input.zoom),visibleWorldHeight=Math.min(input.mapHeight,visiblePixelsY/scaleY/input.zoom),requestedX=input.scrollX+input.viewportWidth/2,requestedY=input.scrollY+input.viewportHeight/2;return{x:Math.min(input.mapWidth-visibleWorldWidth/2,Math.max(visibleWorldWidth/2,requestedX)),y:Math.min(input.mapHeight-visibleWorldHeight/2,Math.max(visibleWorldHeight/2,requestedY))}}

export interface ScreenPoint{x:number;y:number}
const signedArea=(polygon:ScreenPoint[])=>polygon.reduce((sum,point,index)=>{const next=polygon[(index+1)%polygon.length]!;return sum+point.x*next.y-next.x*point.y},0)/2;
const constraints=(polygon:ScreenPoint[],halfWidth:number,halfHeight:number)=>{const clockwise=signedArea(polygon)<0;return polygon.map((point,index)=>{const next=polygon[(index+1)%polygon.length]!,dx=next.x-point.x,dy=next.y-point.y,length=Math.hypot(dx,dy),nx=(clockwise?dy:-dy)/length,ny=(clockwise?-dx:dx)/length;return{nx,ny,minimum:nx*point.x+ny*point.y+Math.abs(nx)*halfWidth+Math.abs(ny)*halfHeight}})};
export function constrainCameraToPolygon(center:ScreenPoint,polygon:ScreenPoint[],halfWidth:number,halfHeight:number):ScreenPoint{const result={...center},edges=constraints(polygon,halfWidth,halfHeight);for(let pass=0;pass<24;pass++){let changed=false;for(const edge of edges){const distance=edge.minimum-edge.nx*result.x-edge.ny*result.y;if(distance>0){result.x+=edge.nx*distance;result.y+=edge.ny*distance;changed=true}}if(!changed)break}return result}
export function minimumZoomForPolygon(polygon:ScreenPoint[],viewportWidth:number,viewportHeight:number):number{let low=.1,high=8;for(let step=0;step<32;step++){const zoom=(low+high)/2,center=constrainCameraToPolygon({x:polygon.reduce((sum,p)=>sum+p.x,0)/polygon.length,y:polygon.reduce((sum,p)=>sum+p.y,0)/polygon.length},polygon,viewportWidth/(2*zoom),viewportHeight/(2*zoom)),fits=constraints(polygon,viewportWidth/(2*zoom),viewportHeight/(2*zoom)).every(edge=>edge.nx*center.x+edge.ny*center.y>=edge.minimum-1e-5);if(fits)high=zoom;else low=zoom}return high}
