export interface Rectangle{left:number;top:number;right:number;bottom:number}
export interface CameraCenterInput{scrollX:number;scrollY:number;viewportWidth:number;viewportHeight:number;zoom:number;canvas:Rectangle;container:Rectangle;mapWidth:number;mapHeight:number}
export interface CameraCenter{x:number;y:number}
export interface VisibleStageRect{left:number;top:number;right:number;bottom:number;width:number;height:number}
export function visibleStageRect(canvas:Rectangle,container:Rectangle,stageWidth:number,stageHeight:number):VisibleStageRect{const scaleX=(canvas.right-canvas.left)/stageWidth,scaleY=(canvas.bottom-canvas.top)/stageHeight,left=(Math.max(canvas.left,container.left)-canvas.left)/scaleX,top=(Math.max(canvas.top,container.top)-canvas.top)/scaleY,right=(Math.min(canvas.right,container.right)-canvas.left)/scaleX,bottom=(Math.min(canvas.bottom,container.bottom)-canvas.top)/scaleY;return{left,top,right,bottom,width:Math.max(0,right-left),height:Math.max(0,bottom-top)}}
export function constrainCameraCenter(input:CameraCenterInput):CameraCenter{const visible=visibleStageRect(input.canvas,input.container,input.mapWidth,input.mapHeight),visibleWorldWidth=Math.min(input.mapWidth,visible.width/input.zoom),visibleWorldHeight=Math.min(input.mapHeight,visible.height/input.zoom),requestedX=input.scrollX+input.viewportWidth/2,requestedY=input.scrollY+input.viewportHeight/2;return{x:Math.min(input.mapWidth-visibleWorldWidth/2,Math.max(visibleWorldWidth/2,requestedX)),y:Math.min(input.mapHeight-visibleWorldHeight/2,Math.max(visibleWorldHeight/2,requestedY))}}

export interface ScreenPoint{x:number;y:number}
export function centerForAnchoredZoom(center:ScreenPoint,pointer:ScreenPoint,viewportCenter:ScreenPoint,currentZoom:number,nextZoom:number):ScreenPoint{const anchor={x:center.x+(pointer.x-viewportCenter.x)/currentZoom,y:center.y+(pointer.y-viewportCenter.y)/currentZoom};return{x:anchor.x-(pointer.x-viewportCenter.x)/nextZoom,y:anchor.y-(pointer.y-viewportCenter.y)/nextZoom}}
export function overviewForPolygon(polygon:ScreenPoint[],viewportWidth:number,viewportHeight:number):{center:ScreenPoint;zoom:number}{const xs=polygon.map(point=>point.x),ys=polygon.map(point=>point.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{center:{x:(minX+maxX)/2,y:(minY+maxY)/2},zoom:Math.min(viewportWidth/(maxX-minX),viewportHeight/(maxY-minY))}}
export function constrainCameraToPolygonBounds(center:ScreenPoint,polygon:ScreenPoint[],halfWidth:number,halfHeight:number):ScreenPoint{const xs=polygon.map(point=>point.x),ys=polygon.map(point=>point.y),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),constrain=(value:number,minimum:number,maximum:number,halfExtent:number)=>minimum+halfExtent>maximum-halfExtent?(minimum+maximum)/2:Math.min(maximum-halfExtent,Math.max(minimum+halfExtent,value));return{x:constrain(center.x,minX,maxX,halfWidth),y:constrain(center.y,minY,maxY,halfHeight)}}
const signedArea=(polygon:ScreenPoint[])=>polygon.reduce((sum,point,index)=>{const next=polygon[(index+1)%polygon.length]!;return sum+point.x*next.y-next.x*point.y},0)/2;
const constraints=(polygon:ScreenPoint[],halfWidth:number,halfHeight:number)=>{const clockwise=signedArea(polygon)<0;return polygon.map((point,index)=>{const next=polygon[(index+1)%polygon.length]!,dx=next.x-point.x,dy=next.y-point.y,length=Math.hypot(dx,dy),nx=(clockwise?dy:-dy)/length,ny=(clockwise?-dx:dx)/length;return{nx,ny,minimum:nx*point.x+ny*point.y+Math.abs(nx)*halfWidth+Math.abs(ny)*halfHeight}})};
export function constrainCameraToPolygon(center:ScreenPoint,polygon:ScreenPoint[],halfWidth:number,halfHeight:number):ScreenPoint{const result={...center},edges=constraints(polygon,halfWidth,halfHeight);for(let pass=0;pass<24;pass++){let changed=false;for(const edge of edges){const distance=edge.minimum-edge.nx*result.x-edge.ny*result.y;if(distance>0){result.x+=edge.nx*distance;result.y+=edge.ny*distance;changed=true}}if(!changed)break}return result}
export function minimumZoomForPolygon(polygon:ScreenPoint[],viewportWidth:number,viewportHeight:number):number{let low=.1,high=8;for(let step=0;step<32;step++){const zoom=(low+high)/2,center=constrainCameraToPolygon({x:polygon.reduce((sum,p)=>sum+p.x,0)/polygon.length,y:polygon.reduce((sum,p)=>sum+p.y,0)/polygon.length},polygon,viewportWidth/(2*zoom),viewportHeight/(2*zoom)),fits=constraints(polygon,viewportWidth/(2*zoom),viewportHeight/(2*zoom)).every(edge=>edge.nx*center.x+edge.ny*center.y>=edge.minimum-1e-5);if(fits)high=zoom;else low=zoom}return high}
